config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'
  resources :home, only: [:index]
  resources :users, path: 'admin/users', controller: 'admin/users'
  root 'home#index'
  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :posts, only: [:new, :create, :edit, :update, :destroy] do
      member do
        put :publish
      end
      resources :comments, only: [:create]
    end
  end

  match ':blog_id', as: :blog_posts_no_prefix,
        via: :get,
        controller: :posts,
        action: :index
  match ':blog_id/:id', as: :blog_post_no_prefix,
        via: :get,
        controller: :posts,
        action: :show
  match '/', as: :blogs_no_prefix,
        via: :get,
        controller: :blogs,
        action: :index
end

app/models/blog.rb
class Blog < ApplicationRecord
  include FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  belongs_to :user
  has_many :posts, dependent: :destroy
  default_scope -> { where(active: true) }

  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  def deactivate!
    update(active: false)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]
  before_action -> { authorize(@blog || Blog.new) }, only: [:new, :edit, :update, :create, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = current_user.blogs
  end

  # GET /blogs/new
  def new
    @blog = current_user.blogs.build
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blogs_url,
                                  notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blogs_url,
                                  notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.deactivate!
    respond_to do |format|
      format.html { redirect_to blogs_url,
                                notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = current_user.blogs.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :slug)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.slim
= simple_form_for(@blog) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :slug

  .form-actions
    = f.button :submit

app/views/blogs/edit.html.slim
.page-header
  = link_to blogs_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @blog, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | blog

= render 'form'

app/views/blogs/index.html.slim
.page-header
  - if current_user.present? && current_user.blogger?
    = link_to new_blog_path, class: 'btn btn-primary' do
      span.glyphicon.glyphicon-plus
      |  New Blog
  h1
    | My blogs

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Name
        th
          | Visitors
        th
          | User
        - if current_user.present? && current_user.blogger?
          th
          th
    tbody
      - @blogs.each do | blog |
        tr
          td
            = link_to blog.name, blog_posts_no_prefix_path(blog)
          td
            = blog.visitors
          td
            = blog.user.try(:name) || 'Anonymous'
          -if current_user.present? && current_user.blogger? && current_user == blog.user
            td
              = link_to 'Edit', edit_blog_path(blog)
            td
              = link_to 'Destroy', blog, method: :delete,
                      data: { confirm: 'Are you sure?' }

app/views/blogs/new.html.slim
.page-header
  = link_to blogs_no_prefix_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | blog

= render 'form'