config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'
  resources :home, only: [:index]
  resources :users, path: 'admin/users', controller: 'admin/users'
  root 'home#index'
  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :posts, only: [:new, :create, :edit, :update, :destroy] do
      member do
        put :publish
      end
      resources :comments, only: [:create]
    end
  end

  match ':blog_id', as: :blog_posts_no_prefix,
        via: :get,
        controller: :posts,
        action: :index
  match ':blog_id/:id', as: :blog_post_no_prefix,
        via: :get,
        controller: :posts,
        action: :show
  match '/', as: :blogs_no_prefix,
        via: :get,
        controller: :blogs,
        action: :index
end

app/models/post.rb
class Post < ApplicationRecord
  include FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :user
  belongs_to :blog
  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  def publish!
    update(published: true)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # The below callback sequence should not be altered, as authorization
  # is dependent on it

  before_action :set_blog, only: [:index, :show]
  before_action :set_blog_from_user, only: [:new, :create, :edit, :update,
                                            :destroy, :publish]
  before_action :build_post, only: [:new, :create]
  before_action :set_post_from_user, only: [:edit, :update, :destroy, :publish]
  before_action -> { authorize(@post) }, only: [:new, :create, :edit, :update,
                                                :destroy]

  # GET /blog/1/posts
  # GET /blog/1/posts.json
  def index
    @posts = PostPolicy::Scope.new(current_user, @blog.posts, @blog).resolve
  end

  # GET /blog/1/posts/1
  # GET /blog/1/posts/1.json
  def show
    @post = @blog.posts.friendly.find(params[:id])
    @comments = @post.comments.joins(:user)
    @comment = @post.comments.build
  end

  # GET /blog/1/posts/new
  def new

  end

  # GET /blog/1/posts/1/edit
  def edit
  end

  # POST /blog/1/posts
  # POST /blog/1/posts.json
  def create
    respond_to do |format|
      if @post.save
        format.html { redirect_to blog_post_no_prefix_path(@blog, @post),
                                  notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog/1/posts/1
  # PATCH/PUT /blog/1/posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to blog_post_no_prefix_path(@blog, @post),
                                  notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog/1/posts/1
  # PATCH/PUT /blog/1/posts/1.json
  def publish
    respond_to do |format|
      if @post.publish!
        format.html { redirect_to blog_post_no_prefix_path(@blog, @post),
                                  notice: 'Post was successfully published.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog/1/posts/1
  # DELETE /blog/1/posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_no_prefix_path(@blog),
                                notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_blog
      @blog =  Blog.friendly.find(params[:blog_id])
    end

    def set_post_from_user
      @post = current_user.posts.friendly.find(params[:id])
    end

    def set_blog_from_user
      @blog = current_user.blogs.friendly.find(params[:blog_id])
    end

    def build_post
      @post = @blog.posts.build(post_params) do |post|
        post.user = current_user
      end
    end

    # Never trust parameters from the scary internet,
    # only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :published) if params.has_key?(:post)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= simple_form_for([@blog, @post]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :content
    = f.input :published

  .form-actions
    = f.button :submit
=javascript_tag do
 | $('#post_content').froalaEditor({
                       fontSizeSelection: true,
                       fontFamilySelection: true,
                       fontSize: ['8', '10', '12', '14', '18', '30', '60', '96']
   });

app/views/posts/edit.html.slim
.page-header
  = link_to blog_posts_path(@blog), class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to blog_post_path(@blog, @post), class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | post

= render 'form'

app/views/posts/index.html.slim
.page-header
  - if current_user.present? && policy(Post.new(user: @blog.user)).create?
    = link_to new_blog_post_path, class: 'btn btn-primary' do
      span.glyphicon.glyphicon-plus
      |  New Post
  h1
    | Listing posts

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Title
        th
          | User
        th
          | Content
        th
          | Views
    tbody
      - @posts.each do | post |
        tr
          td
            = link_to post.title, blog_post_no_prefix_path(@blog, post)
          td
            = post.user.try(:name)
          td
            = post.content.truncate_words(10).html_safe
          td
            = post.views
          - if current_user.present? && policy(post).update?
            td
              = link_to 'Edit', edit_blog_post_path(@blog, post)
            td
              = link_to 'Publish', publish_blog_post_path(@blog, post), method: :put
            td
              = link_to 'Destroy', blog_post_path(@blog, post),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }

app/views/posts/new.html.slim
.page-header
  = link_to blog_posts_no_prefix_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | post

= render 'form'

app/views/posts/show.html.slim
.page-header.pull-right
  = link_to blog_posts_no_prefix_path(@blog), class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
      |  Back To #{@blog.name}
  - if current_user.present? && policy(@post).update?
    = link_to edit_blog_post_path(@blog, @post), class: 'btn btn-primary' do
      span.glyphicon.glyphicon-pencil
      |  Edit
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .post-heading.panel-heading
          h1
            = @post.title
            h4.subheading
              span.meta
                | Posted By #{@post.user.name} on #{@post.created_at.localtime.to_s(:long)}
.container.panel.panel-default
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1.panel-body
      = @post.content.html_safe

= render 'comments/comments', post: @post, blog: @blog