config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'
  resources :home, only: [:index]
  resources :users, path: 'admin/users', controller: 'admin/users'
  root 'home#index'
  resources :blogs, only: [:index, :new, :create, :edit, :update, :destroy] do
    resources :posts, only: [:new, :create, :edit, :update, :destroy] do
      member do
        put :publish
      end
      resources :comments, only: [:create]
    end
  end

  match ':blog_id', as: :blog_posts_no_prefix,
        via: :get,
        controller: :posts,
        action: :index
  match ':blog_id/:id', as: :blog_post_no_prefix,
        via: :get,
        controller: :posts,
        action: :show
  match '/', as: :blogs_no_prefix,
        via: :get,
        controller: :blogs,
        action: :index
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.slim
- if user_signed_in?
  li= link_to 'Edit account', edit_user_registration_path
  li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li= link_to 'Sign in', new_user_session_path
  li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to image_tag('blog.png', size: '24x24'), '/', class: 'navbar-brand'
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li= link_to current_user.email
          li= link_to 'Edit account', edit_user_registration_path
          li= link_to t('blognommer.navigation.sign_out'), destroy_user_session_path, :method => 'delete'
        - else
          li= link_to 'Sign in', new_user_session_path
          li= link_to 'Sign up', new_user_registration_path

app/views/layouts/_navigation_links.html.slim
li
  = link_to t('blognommer.navigation.blogs'), blogs_path if current_user.present? && current_user.blogger?
  = link_to t('blognommer.navigation.users'), users_path if current_user.present? && current_user.admin?

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta[name="current-user" id="#{current_user.try(:id)}"]
    title
      = content_for?(:title) ? yield(:title) : t('blognommer.title')
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Blognommer'}"
    = action_cable_meta_tag
    = stylesheet_link_tag 'application',
            'data-turbolinks-track': true,
            media: 'all'
    = javascript_include_tag 'application',
            'data-turbolinks-track': true
    = csrf_meta_tags
  body
    header
      = render 'layouts/navigation'
    main[role="main"]
      = render 'layouts/messages'
      = yield